sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 265256
# 阿里云OSS配置
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tHCBb72UrnHj8NGJgSC
    access-key-secret: g6tjauuihGGiszzjPddYjMoSHhfMMa
    bucket-name: keevor-sky